# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='profit',
            field=models.BigIntegerField(default=0),
        ),
    ]
