# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('bet_ammount', models.BigIntegerField()),
                ('receive_ammount', models.BigIntegerField()),
                ('result', models.BooleanField(default=False)),
                ('titles', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Titles')),
            ],
        ),
    ]
