# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_titles_profit'),
        ('events', '0002_posts_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=100)),
                ('team_2', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('odds', models.IntegerField()),
                ('result', models.CharField(max_length=100)),
                ('titles', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Titles')),
            ],
        ),
    ]
